spring:
  datasource:
    # Используем переменные окружения для указания логинов, паролей и урлов
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    url: ${DB_URL}
  jpa:
    show_sql: false # Выключаем показ sql запросов
  flyway:
    user: user
    password: password
    url: jdbc:postgresql://postgres:5432/menu_service_db